FROM archlinux/base

ARG CXX_COMPILER=g++
ARG EXTRA_CMAKE_FLAGS=

RUN pacman --noconfirm -Syu archlinux-keyring
RUN pacman --noconfirm -Syu base-devel boost protobuf git cmake python doxygen graphviz unzip capstone

# Install GTIRB
COPY gtirb-arch-artifacts.zip ./gtirb-artifacts.zip
RUN unzip gtirb-artifacts.zip && \
    pacman --noconfirm -U gtirb-git*.pkg.tar.xz && \
    rm gtirb-git*.pkg.tar.xz

# Install gtirb-pprinter
COPY *.pkg.tar.xz ./
RUN pacman --noconfirm -U *.pkg.tar.xz

# build the c++ test
COPY .ci/test-install.cpp test-install.cpp
RUN g++ test-install.cpp -std=c++17 -o test-install -lgtirb_pprinter -lstdc++fs

# run the c++ test
RUN ./test-install

# run the python tests, which will test if the pprinter binaries have been
# installed
COPY . /gt/gtirb-pprinter/
RUN cd /gt/gtirb-pprinter && python3 -m unittest discover tests "*_test.py"
