FROM docker.grammatech.com/rewriting/gtirb/static

RUN apt-get -y update && \
    apt-get -y install \
        gcc-arm-linux-gnueabihf

# Install pip
RUN apt-get -y update && apt-get -y install python3-pip
