FROM ubuntu:18.04

# Use bash for more convenient variable substitution syntax
SHELL ["/bin/bash", "-c"]

# dpkg-dev: for dpkg-scanpackages
# software-properties-common: for add-apt-repository
RUN apt-get -y update && apt-get -y install build-essential curl dpkg-dev software-properties-common \
    unzip

# for boost 1.67
RUN add-apt-repository ppa:mhier/libboost-latest

# setup gtirb package
COPY CMakeLists.txt ./
RUN GTIRB_BRANCH=$((grep -Eo "check_gtirb_branch\([^)]+" CMakeLists.txt || echo "master") | sed 's/check_gtirb_branch(//') && \
    curl -L https://git.grammatech.com/rewriting/gtirb/-/jobs/artifacts/${GTIRB_BRANCH}/download?job=debian-installer-ubuntu18 --output "gtirb-artifacts.zip"
RUN unzip gtirb-artifacts.zip

# setup apt repository
COPY *.deb ./
RUN mkdir -p /gt/apt-repo
RUN cp *.deb /gt/apt-repo/
RUN cd /gt/apt-repo && dpkg-scanpackages . /dev/null > Packages
RUN echo $'\ndeb [trusted=yes] file:/gt/apt-repo ./\n' >> /etc/apt/sources.list

COPY .ci/test-install.cpp test-install.cpp
RUN apt-get update && apt-get install -y --allow-unauthenticated gtirb_pprinter

# build the c++ test
ENV LD_LIBRARY_PATH /usr/local/lib:$LD_LIBRARY_PATH
RUN g++ test-install.cpp -std=c++17 -o test-install -lgtirb_pprinter -lstdc++fs

# run the c++ test
RUN ./test-install

# run the python tests, which will test if the pprinter binaries have been
# installed
COPY . /gt/gtirb-pprinter/
RUN cd /gt/gtirb-pprinter && python3 -m unittest discover tests "*_test.py"
