FROM ubuntu:18.04

RUN apt-get update \
    && apt-get -y install \
    python3 \
    python3-pip \
    clang-format \
    git \
    curl

RUN pip3 install pre-commit

COPY . /gt/gtirb-pprinter
WORKDIR /gt/gtirb-pprinter

RUN pre-commit run --all-files
