# This file runs a test to ensure that this library can be installed once built,
# and C++ code is able to link to it with the proper `-l` flags only.

ARG IMAGE=docker.grammatech.com/rewriting/gtirb-pprinter/ubuntu18-gcc
FROM $IMAGE

# install
ARG INSTALLER="make install"
WORKDIR /gt/gtirb-pprinter/build
RUN $INSTALLER

# delete build directories, to ensure we're not using anything from there
WORKDIR /gt
RUN mv gtirb-pprinter/tests tests
RUN rm -rf gtirb-pprinter

# build the c++ test
COPY .ci/test-install.cpp test-install.cpp

ARG CXX_COMPILER=c++
RUN $CXX_COMPILER test-install.cpp -std=c++17 -o test-install -lgtirb_pprinter -lstdc++fs

# run the c++ test
RUN ./test-install

# run the python tests, which will test if the pprinter binaries have been
# installed
RUN python3 -m unittest discover tests "*_test.py"
