#!/usr/bin/env python3

import sys
from pathlib import Path

TESTS_DIR = Path(__file__).resolve().parent.parent
FAKEBIN_DIR = TESTS_DIR / "fakebin"
sys.path.append(str(FAKEBIN_DIR))
import fakeprog  # noqa: E402

print(Path(__file__).resolve().parent / "fake_llvm_installation", end="")
fakeprog.main()
